yd:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: yd_take_out
    username: ityunbao
    password: 123456
  qiniu:
    ossPath: shd5fhs5b.hd-bkt.clouddn.com
    accesskey: PcV_6bxJxFCpkRGAh03xxoKmqlJfViUEkY63TZSG
    secretkey: 7LpDOYKvfMEJ9GYDfSRkNv7HmcwPBApObtDm4Kzy
    bucketname: yunding11
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx6a7b4bfd924fefa7
    secret: 2051a92fdd37cc120b7f1fae36d1fc30
